include Makefile

.PHONY: run-stream stop-stream

run-stream: ## Start Isaac headless-stream + web-viewer serve stage
	./script/run.sh -t headless-stream -d
	$(MAKE) -C web_viewer run -- -t serve -d

stop-stream: ## Stop web-viewer + Isaac headless-stream
	$(MAKE) -C web_viewer stop
	./script/stop.sh
