#!/usr/bin/env bats
#
# Unit guard for script/runheadless-host-config.sh -- the single place
# that builds the Isaac Sim livestream Kit invocation (base #465/#440;
# replaces the kit_args that lived in the retired run_instance.sh).
#
# Exercised through RUNHEADLESS_DRYRUN=1, which prints the resolved
# command line instead of exec'ing the (absent) Kit launcher. The
# shared parser + per-host config are redirected via HOST_YAML_LIB /
# HOST_YAML_FILE so the script runs outside the container; the livestream
# port env file the post-run hook copies in (#231) via ISAAC_PORTS_ENV_FILE.
#
# Baked into /smoke_test/ next to host_yaml.sh by the devel-test stage.

bats_require_minimum_version 1.5.0

setup() {
  load "${BATS_TEST_DIRNAME}/test_helper"
  WRAP="${BATS_TEST_DIRNAME}/runheadless-host-config.sh"
  export HOST_YAML_LIB="${BATS_TEST_DIRNAME}/host_yaml.sh"
  export RUNHEADLESS_DRYRUN=1
  export HOST_YAML_FILE="/no/such/host.yaml"   # default: no public_ip
  # Default-instance case: no port env set, no port env file.
  unset ISAAC_SIGNAL_PORT ISAAC_MEDIA_PORT ISAAC_API_PORT
  export ISAAC_PORTS_ENV_FILE="/no/such/livestream-ports.env"
  YAML="$(mktemp)"
  PORTS_ENV="$(mktemp)"
  rm -f "${PORTS_ENV}"   # created only by the tests that need it
}

teardown() {
  rm -f "${YAML}" "${PORTS_ENV}"
}

@test "runheadless: first token is the Kit launcher" {
  assert_file_exists "${WRAP}"
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  [ "$(printf '%s\n' "${lines[0]}")" = "/isaac-sim/runheadless.sh" ]
}

@test "runheadless: always emits -v + quitOnSessionEnded=false" {
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '-v'
  echo "${output}" | grep -qx -- '--/app/livestream/nvcf/quitOnSessionEnded=false'
}

@test "runheadless: port env -> livestream port kit-args" {
  export ISAAC_SIGNAL_PORT=49200 ISAAC_MEDIA_PORT=48098 ISAAC_API_PORT=8012
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '--/app/livestream/port=49200'
  echo "${output}" | grep -qx -- '--/app/livestream/fixedHostPort=48098'
  echo "${output}" | grep -qx -- '--/exts/omni.services.transport.server.http/port=8012'
}

@test "runheadless: no port env -> no port kit-args (default instance)" {
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  ! echo "${output}" | grep -q -- '--/app/livestream/port='
  ! echo "${output}" | grep -q -- '--/app/livestream/fixedHostPort='
  ! echo "${output}" | grep -q -- 'transport.server.http/port='
}

@test "runheadless: ports env file -> livestream port kit-args (#234)" {
  printf 'ISAAC_SIGNAL_PORT=49300\nISAAC_MEDIA_PORT=48099\nISAAC_API_PORT=8013\n' \
    > "${PORTS_ENV}"
  export ISAAC_PORTS_ENV_FILE="${PORTS_ENV}"
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '--/app/livestream/port=49300'
  echo "${output}" | grep -qx -- '--/app/livestream/fixedHostPort=48099'
  echo "${output}" | grep -qx -- '--/exts/omni.services.transport.server.http/port=8013'
}

@test "runheadless: absent ports env file -> no port kit-args (#234)" {
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  ! echo "${output}" | grep -q -- '--/app/livestream/port='
  ! echo "${output}" | grep -q -- '--/app/livestream/fixedHostPort='
  ! echo "${output}" | grep -q -- 'transport.server.http/port='
}

@test "runheadless: caller env wins over the ports env file (#234)" {
  printf 'ISAAC_SIGNAL_PORT=49300\nISAAC_MEDIA_PORT=48099\nISAAC_API_PORT=8013\n' \
    > "${PORTS_ENV}"
  export ISAAC_PORTS_ENV_FILE="${PORTS_ENV}"
  export ISAAC_SIGNAL_PORT=49400
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '--/app/livestream/port=49400'
  ! echo "${output}" | grep -q -- '--/app/livestream/port=49300'
  # Keys the caller did not set still come from the file.
  echo "${output}" | grep -qx -- '--/app/livestream/fixedHostPort=48099'
  echo "${output}" | grep -qx -- '--/exts/omni.services.transport.server.http/port=8013'
}

@test "runheadless: ports env file honors only the ISAAC_*_PORT keys (#234)" {
  printf '# generated by the post-run hook\nPATH=/wrong\nISAAC_SIGNAL_PORT=49300\n' \
    > "${PORTS_ENV}"
  export ISAAC_PORTS_ENV_FILE="${PORTS_ENV}"
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '--/app/livestream/port=49300'
  ! echo "${output}" | grep -q -- 'fixedHostPort='
}

@test "runheadless: host.yaml public_ip -> publicEndpointAddress" {
  printf 'network:\n  public_ip: "127.0.0.1"\n' > "${YAML}"
  export HOST_YAML_FILE="${YAML}"
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '--/app/livestream/publicEndpointAddress=127.0.0.1'
}

@test "runheadless: no host.yaml -> no publicEndpointAddress" {
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 0 ]
  ! echo "${output}" | grep -q -- 'publicEndpointAddress'
}

@test "runheadless: invalid public_ip -> rc 1 (shared parser rejects)" {
  printf 'network:\n  public_ip: "a;rm -rf /"\n' > "${YAML}"
  export HOST_YAML_FILE="${YAML}"
  run --separate-stderr "${WRAP}"
  [ "$status" -eq 1 ]
}

@test "runheadless: forwards extra args after the built kit-args" {
  run --separate-stderr "${WRAP}" /work/scene.usd --extra-flag
  [ "$status" -eq 0 ]
  echo "${output}" | grep -qx -- '/work/scene.usd'
  echo "${output}" | grep -qx -- '--extra-flag'
}
